import Head from "next/head";
import { ReactNode } from "react";

type Props = {
  title: string;
  children?: ReactNode;
};

export const Layout = ({ title, children }: Props) => (
  <div>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" href="./favicon.ico" />
    </Head>
    {children}
  </div>
);
